### ISSUE TITLE
Camera function not working Android

### ISSUE THREAD

**Issue by JEAndrew** [StraboSpot/strabo-mobile#368] opened 2017-04-21 16:03 UTC
I can add images from gallery but not via the camera function. I can take the photo and see it and accept it, but it does not get added to the spot

**Comment by jessicagood** [comment] 2017-04-23 06:01
@JEAndrew I might need a little more information as I can't duplicate the issue. What version are you using, how did you install it, exact steps, etc? Can anyone else duplicate it? It seems to be working fine on my Android with the latest version from the Google Play store.

**Comment by JEAndrew** [comment] 2017-04-23 13:01
VerSion 0.18.9, my galaxy 5s is up to date

I installed it through Google play

I can add an image from my phone photo gallery but not by using the strabo app camera. In the app image tab, It will take the photo, ehich I can see in my phone photo gallery. Strabo doesnt add it to the image tab.



Sent from my Verizon 4G LTE smartphone


-------- Original message --------

**Comment by jasonash** [comment] 2017-04-24 14:20
@JEAndrew I just re-installed Strabo from the Google play store, and I can't seem to duplicate the problem. I tried installing on Lollipop, Nougat, and Marshmallow and all worked fine.

Can you tell us what version of Android you are running?

One thing to verify is that the Strabo app has the correct permissions to access images on your device. The easiest way to do this would be to uninstall and reinstall and verify that the permissions are correct when installing.

**Comment by JEAndrew** [comment] 2017-04-24 15:45
OK, I'll reinstall it



________________________________

**Comment by JEAndrew** [comment] 2017-04-24 16:36
Uninstalled and then Reinstalled, but same result with camera and image tab. The app has permission to access and modify my storage.

I updated my galaxy 5s on April 14, I'm running android version 6.0.1



Sent from my Verizon 4G LTE smartphone


-------- Original message --------

**Comment by jasonash** [comment] 2017-04-24 16:47
@JEAndrew I just re-installed StraboSpot from the play store to my Marshmallow (6.0.1) device and I'm able to take pictures and see them in the images tab. 

When you try to add a picture, does the app allow you to take a picture and then crop it? What appears on the images tab once you add an image? Is there a "missing image" placeholder graphic or is the tab empty? After you try adding an image via the camera and it fails, are you able to see the image in your gallery application? If so, can you use strabo to add the image from your gallery instead of the camera?

**Comment by JEAndrew** [comment] 2017-04-24 16:57
The app allows the photo to get taken, then cropped and then select type, then Return to image tab, but no image added



Sent from my Verizon 4G LTE smartphone


-------- Original message --------

**Comment by JEAndrew** [comment] 2017-04-24 16:58
Yes, I can add from gallery



Sent from my Verizon 4G LTE smartphone


-------- Original message --------

**Comment by JEAndrew** [comment] 2017-04-25 19:51
I'm wondering if it's due to the ku server specified security device administrator I have active on my galaxy 5s?



Sent from my Verizon 4G LTE smartphone


-------- Original message --------

**Comment by JEAndrew** [comment] 2017-04-25 20:26
Tested with phone airy Ammonadministration off and the camera still did not add an image to the tab



Sent from my Verizon 4G LTE smartphone


-------- Original message --------

**Comment by jasonash** [comment] 2017-04-25 20:34
@JEAndrew I tried installing again on two devices today. I'm still unable to reproduce this problem. It must be something specific to your device. Are you running any other sort of malware/virus detection software by chance?

**Comment by JEAndrew** [comment] 2017-04-25 20:35
I solved it.  No image will be added using the camera if the GPS is off. No image will be added from gallery if GPS is off and the user chooses the current GPS location option.

Since these images are within a located spot, why do we have this extra location option? I would say we get rid of this extra location business.



Sent from my Verizon 4G LTE smartphone


-------- Original message --------

**Comment by jasonash** [comment] 2017-04-25 20:37
@JEAndrew That's really interesting. I'm not privy to the reason behind the extra location options, but maybe Jessica can remember why we have it. Whatever the case, we can get rid of it if everyone agrees we don't need it.

Thanks for your help with this.

**Comment by jessicagood** [comment] 2017-04-25 22:01
@JEAndrew @jasonash I haven't found the documentaction on who requested this feature or the reasoning yet. I'll keep looking.
 I think part of the thinking was that since a Spot can have varying sizes a user may want to know exactly where a photo was taken within a Spot. This is incomplete though since the same logic could be applied to other features within a Spot and we don't have a way to geotag individual features yet nor do we necessarily want this for every feature within a Spot.

If we do keep this functionality it should be fixed so we don't get the problem you're encountering.

**Comment by jessicagood** [comment] 2017-09-21 18:21
Removed lat and lng from images with commit 256c2fc.

**Closed by jessicagood** 2017-09-21 18:21 UTC
