### ISSUE TITLE
MOBILE PRIORITY: Significant Digits

### ISSUE THREAD

**Issue by rtwilliamsgeo** [StraboSpot/strabo-mobile#358] opened 2017-03-13 15:22 UTC
Many places in the app (in this case strike and dip / trend and plunge measurements) we are showing too many significant digits. For the previous mentioned measurements, these should be rounded to the nearest whole number when displayed.

**Comment by jessicagood** [comment] 2017-03-15 18:40
This is a duplicate of issue https://github.com/StraboSpot/strabo-mobile/issues/354. See comments there.

**Closed by jessicagood** 2017-03-15 18:40 UTC
