### ISSUE TITLE
Select One fields not selecting correctly on iOS

### ISSUE THREAD

**Issue by jessica-azgs** [StraboSpot/strabo-mobile#152] opened 2015-06-17 16:43 UTC
- Make a new station
- Check Measured Plane and enter a strike and dip
- In the Planar Feature Type field select `bedding`
- Now `contact` shows up in the Planar Feature Type field instead of `bedding`
- If you try to select `bedding` again it works correctly

I can't recreate this issue on Android or by emulating devices with Chrome so I can't easily debug. @ginxwar Are you able to debug iOS specific problems better since you have a Mac?

**Comment by ginxwar** [comment] 2015-07-07 06:30
I believe this is now fixed in 4f95289282f6469dffdf1b389569173e468392db.  The issue is a bug tied to Safari.  And although Safari has been "updated" on iOS 8, the internal UIWebView has not.

There's a pretty big angular issue reported about this here https://github.com/angular/angular.js/issues/5132, and a workaround until UIWebView can be fixed.

**Closed** 2015-07-12 04:05 UTC
Labels: bug, priority
